### ISSUE TITLE
How to install amp?

### ISSUE THREAD

**Issue by ainsofs** [keensoft/alfresco-docker-template#8]
Hi, I want to use this set up in dev to test some open source amps. I tried using 201707-GA template but not sure how to install an amp. Trying to install the [js-console amp](https://github.com/share-extras/js-console) for testing. Thxn in Advance

**Comment by DanielFernandezPera** [comment]
Hi,
If you are using this template: https://github.com/keensoft/alfresco-docker-template/tree/master/templates/201707-GA you have to put your amps in alfresco/assets/amps and in share/assets/amps_share. 
After copying the files you have to build images for services again (docker-compose build).

**Comment by ainsofs** [comment]
Thanks this worked in template directory

```
docker-compose build
docker-compose up -d
```
